// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using scorpioweb.Models;
using System;

namespace scorpioweb.Migrations
{
    [DbContext(typeof(penas2Context))]
    partial class penas2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("scorpioweb.Models.Abandonoestado", b =>
                {
                    b.Property<int>("IdAbandonoEstado")
                        .HasColumnName("idAbandonoEstado")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Cuantos")
                        .HasColumnType("int(5)");

                    b.Property<string>("DocumentacionSalirPais")
                        .HasMaxLength(2);

                    b.Property<string>("FamiliaresFuera")
                        .HasMaxLength(2);

                    b.Property<string>("LugaresViaje")
                        .HasMaxLength(200);

                    b.Property<string>("LugaresVivido")
                        .HasMaxLength(200);

                    b.Property<string>("MotivoViaje")
                        .HasMaxLength(200);

                    b.Property<string>("MotivoVivido")
                        .HasMaxLength(200);

                    b.Property<string>("Pasaporte")
                        .HasMaxLength(2);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("TiempoViaje")
                        .HasMaxLength(100);

                    b.Property<string>("TiempoVivido")
                        .HasMaxLength(100);

                    b.Property<string>("ViajaHabitual")
                        .HasMaxLength(2);

                    b.Property<string>("Visa")
                        .HasColumnName("VISA")
                        .HasMaxLength(2);

                    b.Property<string>("VividoFuera")
                        .HasMaxLength(2);

                    b.HasKey("IdAbandonoEstado");

                    b.ToTable("abandonoestado");
                });

            modelBuilder.Entity("scorpioweb.Models.Actividadsocial", b =>
                {
                    b.Property<int>("IdActividadSocial")
                        .HasColumnName("idActividadSocial")
                        .HasColumnType("int(11)");

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<string>("Lugar")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100);

                    b.Property<string>("SePuedeEnterar")
                        .HasMaxLength(2);

                    b.Property<string>("Telefono")
                        .HasMaxLength(10);

                    b.Property<string>("TipoActividad")
                        .HasMaxLength(150);

                    b.HasKey("IdActividadSocial");

                    b.ToTable("actividadsocial");
                });

            modelBuilder.Entity("scorpioweb.Models.Asientofamiliar", b =>
                {
                    b.Property<int>("IdAsientoFamiliar")
                        .HasColumnName("idAsientoFamiliar")
                        .HasColumnType("int(11)");

                    b.Property<string>("Dependencia")
                        .HasMaxLength(2);

                    b.Property<string>("DependenciaExplica")
                        .HasMaxLength(250);

                    b.Property<string>("Domicilio")
                        .HasMaxLength(200);

                    b.Property<int?>("Edad")
                        .HasColumnType("int(11)");

                    b.Property<string>("EnteradoProceso")
                        .HasMaxLength(2);

                    b.Property<string>("HorarioLocalizacion")
                        .HasMaxLength(200);

                    b.Property<string>("Nombre")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("PuedeEnterarse")
                        .HasMaxLength(2);

                    b.Property<string>("Relacion")
                        .HasMaxLength(45);

                    b.Property<string>("Sexo")
                        .HasMaxLength(1);

                    b.Property<string>("Telefono")
                        .HasMaxLength(10);

                    b.Property<string>("TiempoHabitando")
                        .HasMaxLength(45);

                    b.Property<string>("Tipo")
                        .HasMaxLength(45);

                    b.Property<string>("VivenJuntos")
                        .HasMaxLength(2);

                    b.HasKey("IdAsientoFamiliar");

                    b.ToTable("asientofamiliar");
                });

            modelBuilder.Entity("scorpioweb.Models.Consumosustancias", b =>
                {
                    b.Property<int>("IdConsumoSustancias")
                        .HasColumnName("idConsumoSustancias")
                        .HasColumnType("int(11)");

                    b.Property<string>("Cantidad")
                        .HasMaxLength(45);

                    b.Property<string>("Consume")
                        .HasMaxLength(45);

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(45);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(400);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Sustancia")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("UltimoConsumo")
                        .HasColumnType("datetime");

                    b.HasKey("IdConsumoSustancias");

                    b.ToTable("consumosustancias");
                });

            modelBuilder.Entity("scorpioweb.Models.Domicilio", b =>
                {
                    b.Property<int>("IdDomicilio")
                        .HasColumnName("idDomicilio")
                        .HasColumnType("int(11)");

                    b.Property<string>("Calle")
                        .HasMaxLength(200);

                    b.Property<string>("Cp")
                        .HasColumnName("CP")
                        .HasMaxLength(45);

                    b.Property<string>("DomcilioSecundario")
                        .HasMaxLength(45);

                    b.Property<string>("Estado")
                        .HasMaxLength(45);

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<string>("Municipio")
                        .HasMaxLength(45);

                    b.Property<string>("No")
                        .HasMaxLength(45);

                    b.Property<string>("NombreCf")
                        .HasColumnName("NombreCF")
                        .HasMaxLength(45);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(400);

                    b.Property<string>("Pais")
                        .HasMaxLength(45);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Referencias")
                        .HasMaxLength(300);

                    b.Property<string>("ResidenciaHabitual")
                        .HasMaxLength(45);

                    b.Property<string>("Temporalidad")
                        .HasMaxLength(45);

                    b.Property<string>("TipoDomicilio")
                        .HasMaxLength(45);

                    b.Property<string>("TipoUbicacion")
                        .HasMaxLength(45);

                    b.HasKey("IdDomicilio");

                    b.ToTable("domicilio");
                });

            modelBuilder.Entity("scorpioweb.Models.Domiciliosecundario", b =>
                {
                    b.Property<int>("IdDomicilioSecundario")
                        .HasColumnName("idDomicilioSecundario")
                        .HasColumnType("int(11)");

                    b.Property<string>("Calle")
                        .HasMaxLength(200);

                    b.Property<string>("Cp")
                        .HasColumnName("CP")
                        .HasMaxLength(45);

                    b.Property<string>("Estado")
                        .HasMaxLength(45);

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<int>("IdDomicilio")
                        .HasColumnName("idDomicilio")
                        .HasColumnType("int(11)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100);

                    b.Property<string>("Municipio")
                        .HasMaxLength(45);

                    b.Property<string>("No")
                        .HasMaxLength(45);

                    b.Property<string>("NombreCf")
                        .HasColumnName("NombreCF")
                        .HasMaxLength(100);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300);

                    b.Property<string>("Pais")
                        .HasMaxLength(45);

                    b.Property<string>("Referencias")
                        .HasMaxLength(300);

                    b.Property<string>("ResidenciaHabitual")
                        .HasMaxLength(2);

                    b.Property<string>("Temporalidad")
                        .HasMaxLength(45);

                    b.Property<string>("TipoDomicilio")
                        .HasMaxLength(45);

                    b.Property<string>("TipoUbicacion")
                        .HasMaxLength(45);

                    b.HasKey("IdDomicilioSecundario");

                    b.ToTable("domiciliosecundario");
                });

            modelBuilder.Entity("scorpioweb.Models.Estados", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnName("estado")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("scorpioweb.Models.Estudios", b =>
                {
                    b.Property<int>("IdEstudios")
                        .HasColumnName("idEstudios")
                        .HasColumnType("int(11)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150);

                    b.Property<string>("Estudia")
                        .HasMaxLength(45);

                    b.Property<string>("GradoEstudios")
                        .HasMaxLength(45);

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<string>("InstitucionE")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(45);

                    b.HasKey("IdEstudios");

                    b.ToTable("estudios");
                });

            modelBuilder.Entity("scorpioweb.Models.Familiaresforaneos", b =>
                {
                    b.Property<int>("IdFamiliaresForaneos")
                        .HasColumnName("idFamiliaresForaneos")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int(11)");

                    b.Property<string>("EnteradoProceso")
                        .HasMaxLength(2);

                    b.Property<string>("Estado")
                        .HasMaxLength(70);

                    b.Property<string>("FrecuenciaContacto")
                        .HasMaxLength(45);

                    b.Property<string>("Nombre")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200);

                    b.Property<string>("Pais")
                        .HasMaxLength(45);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("PuedeEnterarse")
                        .HasMaxLength(2);

                    b.Property<string>("Relacion")
                        .HasMaxLength(45);

                    b.Property<string>("Sexo")
                        .HasMaxLength(1);

                    b.Property<string>("Telefono")
                        .HasMaxLength(10);

                    b.Property<string>("TiempoConocerlo")
                        .HasMaxLength(45);

                    b.HasKey("IdFamiliaresForaneos");

                    b.ToTable("familiaresforaneos");
                });

            modelBuilder.Entity("scorpioweb.Models.Firmas", b =>
                {
                    b.Property<int>("Idfirmas")
                        .HasColumnName("idfirmas")
                        .HasColumnType("int(11)");

                    b.Property<string>("Codigo")
                        .HasColumnName("codigo")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Libro")
                        .HasColumnName("libro")
                        .HasMaxLength(45);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasMaxLength(200);

                    b.Property<string>("Sexo")
                        .HasColumnName("sexo")
                        .HasMaxLength(45);

                    b.HasKey("Idfirmas");

                    b.ToTable("firmas");
                });

            modelBuilder.Entity("scorpioweb.Models.Municipios", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<int>("EstadosId")
                        .HasColumnName("estados_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnName("municipio")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("municipios");
                });

            modelBuilder.Entity("scorpioweb.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnName("idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Alias")
                        .HasMaxLength(45);

                    b.Property<string>("Celular")
                        .HasMaxLength(45);

                    b.Property<string>("ConsumoSustancias")
                        .HasMaxLength(45);

                    b.Property<string>("Curp")
                        .HasColumnName("CURP")
                        .HasMaxLength(45);

                    b.Property<string>("DatosGeneralescol")
                        .HasMaxLength(100);

                    b.Property<string>("Duracion")
                        .HasMaxLength(45);

                    b.Property<int?>("Edad")
                        .HasColumnType("int(11)");

                    b.Property<string>("EspecifiqueIdioma")
                        .HasMaxLength(45);

                    b.Property<string>("EspecifiqueTraductor")
                        .HasMaxLength(100);

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("Fnacimiento")
                        .HasColumnName("FNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Genero")
                        .HasMaxLength(45);

                    b.Property<string>("Hijos")
                        .HasMaxLength(45);

                    b.Property<string>("LeerEscribir")
                        .HasMaxLength(45);

                    b.Property<string>("Lnestado")
                        .HasColumnName("LNEstado")
                        .HasMaxLength(45);

                    b.Property<string>("Lnlocalidad")
                        .HasColumnName("LNLocalidad")
                        .HasMaxLength(45);

                    b.Property<string>("Lnmunicipio")
                        .HasColumnName("LNMunicipio")
                        .HasMaxLength(45);

                    b.Property<string>("Lnpais")
                        .HasColumnName("LNPais")
                        .HasMaxLength(45);

                    b.Property<string>("Materno")
                        .HasMaxLength(45);

                    b.Property<int?>("Nhijos")
                        .HasColumnName("NHijos")
                        .HasColumnType("int(11)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100);

                    b.Property<int?>("NpersonasVive")
                        .HasColumnName("NPersonasVive")
                        .HasColumnType("int(11)");

                    b.Property<string>("OtroIdioma")
                        .HasMaxLength(45);

                    b.Property<string>("Paterno")
                        .HasMaxLength(45);

                    b.Property<string>("Propiedades")
                        .HasMaxLength(45);

                    b.Property<string>("TelefonoFijo")
                        .HasMaxLength(45);

                    b.Property<string>("Traductor")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("UltimaActualización")
                        .HasColumnType("datetime");

                    b.HasKey("IdPersona");

                    b.ToTable("persona");
                });

            modelBuilder.Entity("scorpioweb.Models.Proceso", b =>
                {
                    b.Property<int>("IdProceso")
                        .HasColumnName("idProceso")
                        .HasColumnType("int(11)");

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("CausaPenal")
                        .HasMaxLength(50);

                    b.Property<string>("Coimputados")
                        .HasMaxLength(45);

                    b.Property<string>("CoimputadosSupervision")
                        .HasMaxLength(45);

                    b.Property<string>("EspecificaFuncionario")
                        .HasMaxLength(100);

                    b.Property<string>("EspecificaRelacion")
                        .HasMaxLength(100);

                    b.Property<string>("Funcionario")
                        .HasMaxLength(45);

                    b.Property<int?>("NoCoimputadosSupervision")
                        .HasColumnType("int(11)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(100);

                    b.Property<string>("RelacionLugar")
                        .HasMaxLength(45);

                    b.Property<string>("RelacionSupervisado")
                        .HasMaxLength(45);

                    b.HasKey("IdProceso", "PersonaIdPersona");

                    b.ToTable("proceso");
                });

            modelBuilder.Entity("scorpioweb.Models.Saludfisica", b =>
                {
                    b.Property<int>("IdSaludFisica")
                        .HasColumnName("idSaludFisica")
                        .HasColumnType("int(11)");

                    b.Property<string>("Discapacidad")
                        .HasMaxLength(2);

                    b.Property<string>("EmbarazoLactancia")
                        .HasMaxLength(2);

                    b.Property<string>("Enfermedad")
                        .HasMaxLength(2);

                    b.Property<string>("EspecifiqueDiscapacidad")
                        .HasMaxLength(100);

                    b.Property<string>("EspecifiqueEnfermedad")
                        .HasMaxLength(100);

                    b.Property<string>("EspecifiqueServicioMedico")
                        .HasMaxLength(45);

                    b.Property<string>("InstitucionServicioMedico")
                        .HasMaxLength(45);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("ServicioMedico")
                        .HasMaxLength(45);

                    b.Property<string>("Tiempo")
                        .HasMaxLength(100);

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(200);

                    b.HasKey("IdSaludFisica");

                    b.ToTable("saludfisica");
                });

            modelBuilder.Entity("scorpioweb.Models.Trabajo", b =>
                {
                    b.Property<int>("IdTrabajo")
                        .HasColumnName("idTrabajo")
                        .HasColumnType("int(11)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150);

                    b.Property<string>("EmpledorJefe")
                        .HasMaxLength(100);

                    b.Property<string>("EnteradoProceso")
                        .HasMaxLength(2);

                    b.Property<string>("Horario")
                        .HasMaxLength(100);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300);

                    b.Property<int>("PersonaIdPersona")
                        .HasColumnName("Persona_idPersona")
                        .HasColumnType("int(11)");

                    b.Property<string>("Puesto")
                        .HasMaxLength(45);

                    b.Property<string>("Salario")
                        .HasMaxLength(45);

                    b.Property<string>("SePuedeEnterar")
                        .HasMaxLength(2);

                    b.Property<string>("Telefono")
                        .HasMaxLength(45);

                    b.Property<string>("TemporalidadSalario")
                        .HasMaxLength(45);

                    b.Property<string>("TiempoTrabajano")
                        .HasMaxLength(45);

                    b.Property<string>("TipoOcupacion")
                        .HasMaxLength(150);

                    b.Property<string>("Trabaja")
                        .HasMaxLength(2);

                    b.HasKey("IdTrabajo");

                    b.ToTable("trabajo");
                });
#pragma warning restore 612, 618
        }
    }
}
